services:
  - type: web
    name: order-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn order_project.wsgi:application
    envVars:
      - key: GOOGLE_CREDENTIALS
        value: '{{  }}'
