services:
  - type: web
    name: order-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn order_system.wsgi:application
    # disk:
    #   name: order-system-data
    #   mountPath: /mnt/data
    # instanceCount: 1
    # autoDeploy: true